services:
  db:
    image: postgres:16-alpine
    container_name: t3chat-cloneathon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_nextjs:/var/lib/postgresql/data

volumes:
  postgres_data_nextjs:
    driver: local
